# Generated by Django 2.1 on 2018-09-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=30, null=True)),
                ('d_age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('place', models.CharField(max_length=50, null=True)),
                ('specification', models.CharField(max_length=50, null=True)),
                ('cabin_no', models.IntegerField(null=True)),
                ('birth_date', models.DateField(null=True)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('p_name', models.CharField(max_length=30, null=True)),
                ('p_age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('place', models.CharField(max_length=50, null=True)),
                ('problem', models.CharField(max_length=50, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('Doctor_name', models.CharField(max_length=30, null=True)),
                ('cabin_no', models.IntegerField(null=True)),
                ('d_contact', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('d_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Doctor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('cabin_no', 'email', 'contact')},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('cabin_no', 'email', 'contact')},
        ),
    ]
